#!/usr/bin/env php
<?php

function render($tag, $type)
{
    $v = strstr($tag, '-', true) ?: $tag;
    if (version_compare($v, '8.0', '>=') or $v == 'rc' or $v == 'latest' or $v == 'alpine') {
        $CFLAGS = 'CFLAGS="$CFLAGS -D_GNU_SOURCE"';
    } else {
        $CFLAGS = '';
    }
    ob_start();
    include __DIR__ . '/templates/' . $type . '.php';
    $content = ob_get_clean();
    if (!is_dir(__DIR__ . '/' . $tag)) {
        mkdir(__DIR__ . '/' . $tag);
    }
    file_put_contents(__DIR__ . '/' . $tag . '/Dockerfile', $content);
}

$debian_tags = ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', 'rc', 'latest'];
foreach ($debian_tags as $tag) {
    render($tag, 'debian');
}

$alpine_tags = ['7.2-alpine', '7.3-alpine', '7.4-alpine', '8.0-alpine', '8.1-alpine', '8.2-alpine', 'rc-alpine', 'alpine'];
foreach ($alpine_tags as $tag) {
    render($tag, 'alpine');
}
