#!/usr/bin/env php
<?php

const alpine_version = '3.18';
const debian_version = 'bullseye';

function render($version, $type)
{
    $v = strstr($version, '-', true) ?: $version;
    if (version_compare($v, '8.0', '>=') or $v == 'rc' or $v == 'latest' or $v == 'alpine') {
        $CFLAGS = 'CFLAGS="$CFLAGS -D_GNU_SOURCE"';
    } else {
        $CFLAGS = '';
    }

    $alpine = str_contains($version, 'alpine');
    if (!$alpine) {
        // 7.2 does not have bullseye
        if ($version === '7.2') {
            $tag = $version;
        } elseif ($version === 'rc' or $version == 'latest') {
            $tag = debian_version;
        } else {
            $tag = $version . '-' . debian_version;
        }
    } else {
        if (version_compare($v, '8.1', '>=')) {
            $tag = $version . alpine_version;
        } else {
            $tag = $version;
        }
    }

    ob_start();
    include __DIR__ . '/templates/' . $type . '.php';
    $content = ob_get_clean();
    $dockerFile = __DIR__ . '/' . $version . '/Dockerfile';

    if (!is_dir(dirname($dockerFile))) {
        mkdir(dirname($dockerFile));
    }
    file_put_contents($dockerFile, $content);
}

$debian_versions = ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', 'rc', 'latest'];
foreach ($debian_versions as $v) {
    render($v, 'debian');
}

$alpine_versions = ['7.2-alpine', '7.3-alpine', '7.4-alpine', '8.0-alpine', '8.1-alpine', '8.2-alpine', '8.3-alpine', 'rc-alpine', 'alpine'];
foreach ($alpine_versions as $v) {
    render($v, 'alpine');
}
