name: Build Versioned Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_versioned_images:
    if: ${{ github.repository == 'swoole/php-docker' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', 'rc']

    name: The image for PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set output parameters
        id: params
        run: |
          echo "::set-output name=full_names::phpswoole/php:${{ matrix.php }}"

      - name: Build and push Docker image phpswoole/php:${{ matrix.php }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.php }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.params.outputs.full_names }}

      - name: Image digest of phpswoole/php:${{ matrix.php }}
        run: echo ${{ steps.docker_build.outputs.digest }}
