name: Build Latest Alpine Images

on:
  schedule:
    - cron: '47 4 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_latest_images:
    if: ${{ github.repository == 'swoole/php-docker' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set full names of the Docker image
        id: set_full_names
        run: echo "::set-output name=full_names::phpswoole/php:${{ matrix.php }}-alpine"

      - name: Build and push Docker image phpswoole/php:${{ matrix.php }}-alpine
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: alpine/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.set_full_names.outputs.full_names }}

      - name: Image digest of phpswoole/php:${{ matrix.php }}-alpine
        run: echo ${{ steps.docker_build.outputs.digest }}
